import { useState } from "react";
import { 
  FileText, 
  Download, 
  Copy, 
  CheckCircle,
  Hash,
  Clock,
  Cpu,
  Shield,
  User,
  MapPin
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { jsPDF } from "jspdf";
import type { VerdictType } from "./AnalysisResults";

interface ForensicReportProps {
  mediaHash: string;
  verdict: VerdictType;
  confidence: number;
  detectionMethods: string[];
  timestamp: Date;
  deviceId: string;
  fileName: string;
  fileSize: number;
  processingTime: number;
}

const ForensicReport = ({
  mediaHash,
  verdict,
  confidence,
  detectionMethods,
  timestamp,
  deviceId,
  fileName,
  fileSize,
  processingTime
}: ForensicReportProps) => {
  const [copied, setCopied] = useState(false);
  const [generating, setGenerating] = useState(false);

  const copyToClipboard = async () => {
    const reportText = generateReportText();
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateReportText = () => {
    return `
SHANSHIELD AUTHENTICITY ANALYSIS REPORT
========================================
Classification: FOR RESEARCH/REFERENCE ONLY

LEGAL DISCLAIMER
----------------
This analysis is INDICATIVE ONLY and does not constitute legal evidence.
Results require independent verification by certified forensic professionals.
Not admissible in court without expert corroboration.
Compliant with: EU AI Act (2024), NIST AI RMF, ISO/IEC 27001, GDPR Art. 22

MEDIA INFORMATION
-----------------
File Name: ${fileName}
File Size: ${(fileSize / 1024 / 1024).toFixed(2)} MB
SHA-256 Hash: ${mediaHash}

ANALYSIS RESULTS
----------------
Verdict: ${verdict.toUpperCase().replace('_', ' ')}
Confidence: ${confidence}%
Processing Time: ${processingTime.toFixed(2)}s

DETECTION METHODS EMPLOYED
--------------------------
${detectionMethods.map((m, i) => `${i + 1}. ${m}`).join('\n')}

METADATA
--------
Analysis Timestamp: ${timestamp.toISOString()}
Device ID: ${deviceId}
System Version: SHANSHIELD v4.2.0 (Experimental)

VERIFICATION NOTES
------------------
This report was generated by SHANSHIELD Agentic AI System.
Report Hash: ${mediaHash.substring(0, 16)}...${mediaHash.substring(mediaHash.length - 16)}

For official investigations, consult certified digital forensic professionals.
========================================
    `.trim();
  };

  const handleDownload = async () => {
    setGenerating(true);
    
    try {
      // Generate real PDF using jsPDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Header
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("SHANSHIELD", pageWidth / 2, 20, { align: "center" });
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Authenticity Verification Report", pageWidth / 2, 28, { align: "center" });
      
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Classification: FOR OFFICIAL USE ONLY", pageWidth / 2, 35, { align: "center" });
      doc.setTextColor(0);
      
      // Horizontal line
      doc.setLineWidth(0.5);
      doc.line(20, 40, pageWidth - 20, 40);
      
      // Media Information Section
      let yPos = 50;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("MEDIA INFORMATION", 20, yPos);
      
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`File Name: ${fileName}`, 20, yPos);
      yPos += 7;
      doc.text(`File Size: ${(fileSize / 1024 / 1024).toFixed(2)} MB`, 20, yPos);
      yPos += 7;
      doc.text(`SHA-256 Hash:`, 20, yPos);
      yPos += 5;
      doc.setFontSize(8);
      doc.text(mediaHash, 25, yPos);
      
      // Analysis Results Section
      yPos += 15;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("ANALYSIS RESULTS", 20, yPos);
      
      yPos += 10;
      doc.setFontSize(12);
      const verdictColor = verdict === 'authentic' || verdict === 'likely_authentic' 
        ? [34, 197, 94] : verdict === 'suspicious' 
        ? [251, 191, 36] : [239, 68, 68];
      doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
      doc.text(`Verdict: ${verdict.toUpperCase().replace('_', ' ')}`, 20, yPos);
      doc.setTextColor(0);
      
      yPos += 8;
      doc.setFontSize(10);
      doc.text(`Confidence: ${confidence}%`, 20, yPos);
      yPos += 7;
      doc.text(`Processing Time: ${processingTime.toFixed(2)}s`, 20, yPos);
      
      // Detection Methods Section
      yPos += 15;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("DETECTION METHODS EMPLOYED", 20, yPos);
      
      yPos += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      detectionMethods.forEach((method, i) => {
        doc.text(`${i + 1}. ${method}`, 25, yPos);
        yPos += 6;
      });
      
      // Metadata Section
      yPos += 10;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("METADATA", 20, yPos);
      
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Analysis Timestamp: ${timestamp.toISOString()}`, 20, yPos);
      yPos += 7;
      doc.text(`Device ID: ${deviceId}`, 20, yPos);
      yPos += 7;
      doc.text(`System Version: SHANSHIELD v4.2.0`, 20, yPos);
      
      // Footer
      yPos = doc.internal.pageSize.getHeight() - 30;
      doc.setLineWidth(0.5);
      doc.line(20, yPos, pageWidth - 20, yPos);
      
      yPos += 10;
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text("This report was generated by SHANSHIELD Agentic AI System.", pageWidth / 2, yPos, { align: "center" });
      yPos += 5;
      doc.text(`Report Hash: ${mediaHash.substring(0, 16)}...${mediaHash.substring(mediaHash.length - 16)}`, pageWidth / 2, yPos, { align: "center" });
      yPos += 5;
      doc.text("IIT Delhi ERAKSHA Hackathon 2026", pageWidth / 2, yPos, { align: "center" });
      
      // Save the PDF
      doc.save(`SHANSHIELD_Report_${timestamp.getTime()}.pdf`);
    } catch (error) {
      console.error("PDF generation error:", error);
      // Fallback to text export
      const reportText = generateReportText();
      const blob = new Blob([reportText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `SHANSHIELD_Report_${timestamp.getTime()}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
    
    setGenerating(false);
  };

  const verdictColor = {
    authentic: 'text-success',
    likely_authentic: 'text-success/80',
    suspicious: 'text-warning',
    deepfake: 'text-destructive'
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-primary" />
          <h3 className="font-display text-sm font-bold text-foreground tracking-widest uppercase">
            Forensic-Grade Report
          </h3>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={copyToClipboard}
            className="border-border/50 hover:border-primary"
          >
            {copied ? (
              <>
                <CheckCircle className="w-4 h-4 mr-2 text-success" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-2" />
                Copy
              </>
            )}
          </Button>
          <Button
            variant="default"
            size="sm"
            onClick={handleDownload}
            disabled={generating}
            className="bg-primary hover:bg-primary/90"
          >
            {generating ? (
              <>
                <div className="w-4 h-4 mr-2 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="w-4 h-4 mr-2" />
                Generate Report
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Report Preview */}
      <div className="bg-card/50 border border-border/30 rounded-lg overflow-hidden">
        {/* Header */}
        <div className="bg-primary/10 border-b border-primary/20 p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Shield className="w-8 h-8 text-primary" />
              <div>
                <h4 className="font-display text-lg font-bold text-foreground tracking-wide">
                  SHANSHIELD
                </h4>
                <p className="text-xs text-muted-foreground">
                  Authenticity Verification Report
                </p>
              </div>
            </div>
            <div className="text-right">
              <span className="text-xs text-muted-foreground block">Classification</span>
              <span className="text-xs font-display tracking-wider text-amber-400">
                FOR RESEARCH USE ONLY
              </span>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-4 space-y-4">
          {/* Media Hash */}
          <div className="flex items-start gap-3 p-3 bg-background/50 rounded-lg">
            <Hash className="w-5 h-5 text-primary mt-0.5" />
            <div className="flex-1">
              <span className="text-xs text-muted-foreground block mb-1">SHA-256 Hash</span>
              <code className="text-xs font-mono text-foreground break-all">
                {mediaHash}
              </code>
            </div>
          </div>

          {/* Verdict */}
          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 bg-background/50 rounded-lg">
              <span className="text-xs text-muted-foreground block mb-1">Verdict</span>
              <span className={cn(
                "font-display text-lg font-bold tracking-wide",
                verdictColor[verdict]
              )}>
                {verdict.toUpperCase().replace('_', ' ')}
              </span>
            </div>
            <div className="p-3 bg-background/50 rounded-lg">
              <span className="text-xs text-muted-foreground block mb-1">Confidence</span>
              <span className={cn(
                "font-display text-lg font-bold",
                verdictColor[verdict]
              )}>
                {confidence}%
              </span>
            </div>
          </div>

          {/* Detection Methods */}
          <div className="p-3 bg-background/50 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Cpu className="w-4 h-4 text-primary" />
              <span className="text-xs text-muted-foreground">Detection Methods</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {detectionMethods.map((method, index) => (
                <span 
                  key={index}
                  className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full border border-primary/20"
                >
                  {method}
                </span>
              ))}
            </div>
          </div>

          {/* Metadata Grid */}
          <div className="grid grid-cols-3 gap-3">
            <div className="p-3 bg-background/50 rounded-lg">
              <div className="flex items-center gap-2 mb-1">
                <Clock className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Timestamp</span>
              </div>
              <span className="text-xs font-mono text-foreground">
                {timestamp.toISOString().replace('T', ' ').substring(0, 19)}
              </span>
            </div>
            <div className="p-3 bg-background/50 rounded-lg">
              <div className="flex items-center gap-2 mb-1">
                <User className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Device ID</span>
              </div>
              <span className="text-xs font-mono text-foreground">
                {deviceId}
              </span>
            </div>
            <div className="p-3 bg-background/50 rounded-lg">
              <div className="flex items-center gap-2 mb-1">
                <MapPin className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Processing</span>
              </div>
              <span className="text-xs font-mono text-foreground">
                {processingTime.toFixed(2)}s
              </span>
            </div>
          </div>

          {/* Export Options */}
          <div className="border-t border-border/30 pt-4 mt-4">
            <span className="text-xs text-muted-foreground block mb-2">
              Export for:
            </span>
            <div className="flex flex-wrap gap-2">
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Law Enforcement
              </span>
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Intelligence Agencies
              </span>
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Legal Review
              </span>
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Forensic Archive
              </span>
            </div>
          </div>
        </div>

        {/* Footer with Legal Notice */}
        <div className="bg-muted/20 border-t border-border/30 p-3 space-y-2">
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>SHANSHIELD v4.2.0 (Experimental)</span>
            <span>Research Prototype</span>
          </div>
          <p className="text-[9px] text-muted-foreground/60 text-center">
            ⚠️ Indicative analysis only. Not legal evidence. Requires independent forensic verification.
            Compliant with EU AI Act, NIST AI RMF, ISO/IEC 27001.
          </p>
        </div>
      </div>
    </div>
  );
};

export default ForensicReport;
