import { useState } from "react";
import { 
  FileText, 
  Download, 
  Copy, 
  CheckCircle,
  Hash,
  Clock,
  Cpu,
  Shield,
  User,
  MapPin
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { VerdictType } from "./AnalysisResults";

interface ForensicReportProps {
  mediaHash: string;
  verdict: VerdictType;
  confidence: number;
  detectionMethods: string[];
  timestamp: Date;
  deviceId: string;
  fileName: string;
  fileSize: number;
  processingTime: number;
}

const ForensicReport = ({
  mediaHash,
  verdict,
  confidence,
  detectionMethods,
  timestamp,
  deviceId,
  fileName,
  fileSize,
  processingTime
}: ForensicReportProps) => {
  const [copied, setCopied] = useState(false);
  const [generating, setGenerating] = useState(false);

  const copyToClipboard = async () => {
    const reportText = generateReportText();
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateReportText = () => {
    return `
SHANSHIELD AUTHENTICITY VERIFICATION REPORT
============================================
Classification: FOR OFFICIAL USE ONLY

MEDIA INFORMATION
-----------------
File Name: ${fileName}
File Size: ${(fileSize / 1024 / 1024).toFixed(2)} MB
SHA-256 Hash: ${mediaHash}

ANALYSIS RESULTS
----------------
Verdict: ${verdict.toUpperCase().replace('_', ' ')}
Confidence: ${confidence}%
Processing Time: ${processingTime.toFixed(2)}s

DETECTION METHODS EMPLOYED
--------------------------
${detectionMethods.map((m, i) => `${i + 1}. ${m}`).join('\n')}

METADATA
--------
Analysis Timestamp: ${timestamp.toISOString()}
Device ID: ${deviceId}
System Version: SHANSHIELD v1.0

VERIFICATION SEAL
-----------------
This report was generated by SHANSHIELD Agentic AI System.
Report Hash: ${mediaHash.substring(0, 16)}...${mediaHash.substring(mediaHash.length - 16)}

============================================
IIT Delhi ERAKSHA Hackathon 2024
    `.trim();
  };

  const handleDownload = async () => {
    setGenerating(true);
    
    // Simulate PDF generation
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    const reportText = generateReportText();
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SHANSHIELD_Report_${timestamp.getTime()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    setGenerating(false);
  };

  const verdictColor = {
    authentic: 'text-success',
    likely_authentic: 'text-success/80',
    suspicious: 'text-warning',
    deepfake: 'text-destructive'
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-primary" />
          <h3 className="font-display text-sm font-bold text-foreground tracking-widest uppercase">
            Forensic-Grade Report
          </h3>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={copyToClipboard}
            className="border-border/50 hover:border-primary"
          >
            {copied ? (
              <>
                <CheckCircle className="w-4 h-4 mr-2 text-success" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-2" />
                Copy
              </>
            )}
          </Button>
          <Button
            variant="default"
            size="sm"
            onClick={handleDownload}
            disabled={generating}
            className="bg-primary hover:bg-primary/90"
          >
            {generating ? (
              <>
                <div className="w-4 h-4 mr-2 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="w-4 h-4 mr-2" />
                Generate Report
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Report Preview */}
      <div className="bg-card/50 border border-border/30 rounded-lg overflow-hidden">
        {/* Header */}
        <div className="bg-primary/10 border-b border-primary/20 p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Shield className="w-8 h-8 text-primary" />
              <div>
                <h4 className="font-display text-lg font-bold text-foreground tracking-wide">
                  SHANSHIELD
                </h4>
                <p className="text-xs text-muted-foreground">
                  Authenticity Verification Report
                </p>
              </div>
            </div>
            <div className="text-right">
              <span className="text-xs text-muted-foreground block">Classification</span>
              <span className="text-xs font-display tracking-wider text-warning">
                FOR OFFICIAL USE ONLY
              </span>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-4 space-y-4">
          {/* Media Hash */}
          <div className="flex items-start gap-3 p-3 bg-background/50 rounded-lg">
            <Hash className="w-5 h-5 text-primary mt-0.5" />
            <div className="flex-1">
              <span className="text-xs text-muted-foreground block mb-1">SHA-256 Hash</span>
              <code className="text-xs font-mono text-foreground break-all">
                {mediaHash}
              </code>
            </div>
          </div>

          {/* Verdict */}
          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 bg-background/50 rounded-lg">
              <span className="text-xs text-muted-foreground block mb-1">Verdict</span>
              <span className={cn(
                "font-display text-lg font-bold tracking-wide",
                verdictColor[verdict]
              )}>
                {verdict.toUpperCase().replace('_', ' ')}
              </span>
            </div>
            <div className="p-3 bg-background/50 rounded-lg">
              <span className="text-xs text-muted-foreground block mb-1">Confidence</span>
              <span className={cn(
                "font-display text-lg font-bold",
                verdictColor[verdict]
              )}>
                {confidence}%
              </span>
            </div>
          </div>

          {/* Detection Methods */}
          <div className="p-3 bg-background/50 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Cpu className="w-4 h-4 text-primary" />
              <span className="text-xs text-muted-foreground">Detection Methods</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {detectionMethods.map((method, index) => (
                <span 
                  key={index}
                  className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full border border-primary/20"
                >
                  {method}
                </span>
              ))}
            </div>
          </div>

          {/* Metadata Grid */}
          <div className="grid grid-cols-3 gap-3">
            <div className="p-3 bg-background/50 rounded-lg">
              <div className="flex items-center gap-2 mb-1">
                <Clock className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Timestamp</span>
              </div>
              <span className="text-xs font-mono text-foreground">
                {timestamp.toISOString().replace('T', ' ').substring(0, 19)}
              </span>
            </div>
            <div className="p-3 bg-background/50 rounded-lg">
              <div className="flex items-center gap-2 mb-1">
                <User className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Device ID</span>
              </div>
              <span className="text-xs font-mono text-foreground">
                {deviceId}
              </span>
            </div>
            <div className="p-3 bg-background/50 rounded-lg">
              <div className="flex items-center gap-2 mb-1">
                <MapPin className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Processing</span>
              </div>
              <span className="text-xs font-mono text-foreground">
                {processingTime.toFixed(2)}s
              </span>
            </div>
          </div>

          {/* Export Options */}
          <div className="border-t border-border/30 pt-4 mt-4">
            <span className="text-xs text-muted-foreground block mb-2">
              Export for:
            </span>
            <div className="flex flex-wrap gap-2">
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Law Enforcement
              </span>
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Intelligence Agencies
              </span>
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Legal Review
              </span>
              <span className="text-xs bg-card border border-border/50 px-2 py-1 rounded">
                Forensic Archive
              </span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="bg-muted/20 border-t border-border/30 p-3">
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>SHANSHIELD v1.0</span>
            <span>IIT Delhi ERAKSHA Hackathon 2024</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ForensicReport;
