import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                    SHANSHIELD CLOUD ML ANALYSIS                            ║
 * ║                                                                           ║
 * ║  Real AI-powered Deepfake Detection using Google Gemini 3                 ║
 * ║  Backend: Supabase Edge Functions (Lovable Cloud)                         ║
 * ║  Model: google/gemini-3-flash-preview (Gemini 3 Hackathon)                ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

interface OfflineAnalysisData {
  score: number;
  signals: string[];
  details: Record<string, { score: number; description: string }>;
}

interface MLAnalysisResult {
  verdict: 'deepfake' | 'suspicious' | 'likely_authentic' | 'authentic';
  confidence: number;
  mlSignals: string[];
  reasoning: string;
  aiToolDetected: string | null;
  manipulationTypes: string[];
  geminiVersion?: string;
}

/**
 * System prompt for deepfake analysis - Optimized for Gemini 3
 */
const DEEPFAKE_ANALYSIS_PROMPT = `You are ShanShield, an expert AI system specialized in detecting AI-generated and manipulated media (deepfakes). You are powered by Google Gemini 3 - the most advanced multimodal AI model. Analyze the provided image for signs of AI generation or manipulation with extreme precision.

ANALYZE FOR:
1. **AI Generation Artifacts**: Look for telltale signs of AI image generators like:
   - Unnatural skin textures or overly smooth areas
   - Inconsistent lighting or shadows
   - Warped or asymmetric facial features (especially ears, teeth, hands)
   - Artifacts around hair, teeth, ears, or jewelry
   - Unnatural eye reflections or catchlights (different shapes in each eye)
   - Background inconsistencies or blurring patterns
   - Repetitive textures or patterns
   - Text or symbols that are distorted or nonsensical

2. **Face Manipulation Signs**: Check for:
   - Boundary artifacts around face edges
   - Mismatched skin tones between face and body
   - Unnatural blending zones
   - Inconsistent aging or texture between regions
   - Face swap seams or warping

3. **Technical Artifacts**: Identify:
   - Compression artifacts inconsistent with natural photos
   - Color banding or posterization
   - Noise pattern irregularities (AI images have uniform noise)
   - JPEG grid misalignment suggesting re-encoding

4. **AI Tool Signatures**: Try to identify if generated by:
   - Midjourney (characteristic art style, dramatic lighting)
   - Stable Diffusion (texture patterns, hand/finger issues)
   - DALL-E (smooth gradients, distinct style)
   - Face swap tools (boundary issues, lighting mismatches)
   - StyleGAN (characteristic eye/hair artifacts)
   - Sora/Runway (video generation artifacts)
   - Voice cloning (ElevenLabs, Resemble.AI)

5. **Quantum Entropy Markers**: Analyze for:
   - Unnaturally low entropy in textures (AI over-smoothing)
   - Periodic patterns that indicate algorithmic generation
   - Statistical anomalies in pixel distributions

RESPOND WITH EXACTLY THIS JSON FORMAT:
{
  "verdict": "deepfake" | "suspicious" | "likely_authentic" | "authentic",
  "confidence": <number 0-100>,
  "signals": ["signal1", "signal2", ...],
  "reasoning": "<detailed explanation in 2-3 sentences>",
  "aiToolDetected": "<tool name or null>",
  "manipulationTypes": ["type1", "type2", ...]
}

VERDICT GUIDELINES:
- "authentic": High confidence (85%+) the image is a real, unmanipulated photo
- "likely_authentic": Some minor concerns but probably genuine (60-84%)
- "suspicious": Notable anomalies suggesting possible manipulation (40-59%)
- "deepfake": Strong evidence of AI generation or manipulation (0-39% authentic confidence, meaning 60%+ deepfake confidence)

Be conservative - real photos often have compression artifacts. Only flag as deepfake if you see clear AI signatures.`;

/**
 * Analyze media using Lovable AI Gateway with Gemini Vision
 */
async function analyzeWithGeminiVision(
  imageBase64: string | null,
  mediaType: string,
  fileName: string,
  offlineAnalysis: OfflineAnalysisData
): Promise<MLAnalysisResult> {
  const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  
  if (!LOVABLE_API_KEY) {
    throw new Error("LOVABLE_API_KEY is not configured");
  }

  // Build the messages array
  const messages: any[] = [
    { role: "system", content: DEEPFAKE_ANALYSIS_PROMPT }
  ];

  // Build user message with or without image
  if (imageBase64) {
    // Extract the base64 data (remove data:image/...;base64, prefix if present)
    let base64Data = imageBase64;
    let mimeType = "image/jpeg";
    
    if (imageBase64.startsWith("data:")) {
      const matches = imageBase64.match(/^data:([^;]+);base64,(.+)$/);
      if (matches) {
        mimeType = matches[1];
        base64Data = matches[2];
      }
    }

    messages.push({
      role: "user",
      content: [
        {
          type: "image_url",
          image_url: {
            url: `data:${mimeType};base64,${base64Data}`
          }
        },
        {
          type: "text",
          text: `Analyze this ${mediaType} file "${fileName}" for deepfake/AI-generation signs.\n\nOffline analysis data for context:\n- Preliminary score: ${offlineAnalysis.score}/100 (higher = more suspicious)\n- Detected signals: ${offlineAnalysis.signals.join(", ") || "None"}\n\nProvide your analysis in the exact JSON format specified.`
        }
      ]
    });
  } else {
    // No image provided - analyze based on offline data only
    messages.push({
      role: "user",
      content: `Analyze this ${mediaType} file "${fileName}" for deepfake potential based on the offline analysis data:\n\n- Preliminary score: ${offlineAnalysis.score}/100 (higher = more suspicious)\n- Detected signals: ${offlineAnalysis.signals.join(", ") || "None"}\n- Analysis details: ${JSON.stringify(offlineAnalysis.details, null, 2)}\n\nBased on this forensic data, provide your assessment in the exact JSON format specified. Since no visual is available, weight the offline analysis heavily.`
    });
  }

  console.log("Calling Lovable AI Gateway with Gemini 3 Flash Preview...");
  
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${LOVABLE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-3-flash-preview",
      messages,
      temperature: 0.2, // Lower temperature for more precise analysis
      max_tokens: 1500,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("AI Gateway error:", response.status, errorText);
    
    if (response.status === 429) {
      throw new Error("RATE_LIMIT");
    }
    if (response.status === 402) {
      throw new Error("PAYMENT_REQUIRED");
    }
    throw new Error(`AI Gateway error: ${response.status}`);
  }

  const data = await response.json();
  console.log("AI Gateway response received");
  
  const content = data.choices?.[0]?.message?.content;
  
  if (!content) {
    throw new Error("No response content from AI");
  }

  // Parse the JSON response
  try {
    // Extract JSON from the response (it might be wrapped in markdown code blocks)
    let jsonStr = content;
    const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (jsonMatch) {
      jsonStr = jsonMatch[1].trim();
    } else {
      // Try to find JSON object directly
      const objMatch = content.match(/\{[\s\S]*\}/);
      if (objMatch) {
        jsonStr = objMatch[0];
      }
    }

    const parsed = JSON.parse(jsonStr);
    
    return {
      verdict: parsed.verdict || 'suspicious',
      confidence: Math.max(0, Math.min(100, parsed.confidence || 50)),
      mlSignals: parsed.signals || [],
      reasoning: parsed.reasoning || 'Analysis completed',
      aiToolDetected: parsed.aiToolDetected || null,
      manipulationTypes: parsed.manipulationTypes || [],
      geminiVersion: 'gemini-3-flash-preview',
    };
  } catch (parseError) {
    console.error("Failed to parse AI response:", content);
    // Return a fallback based on offline analysis
    return {
      verdict: offlineAnalysis.score > 70 ? 'suspicious' : 'likely_authentic',
      confidence: 100 - offlineAnalysis.score,
      mlSignals: ['AI analysis parsing error - using offline data'],
      reasoning: 'Cloud ML analysis encountered an issue. Results based on offline forensic analysis.',
      aiToolDetected: null,
      manipulationTypes: [],
    };
  }
}

// ============================================================================
// HTTP SERVER
// ============================================================================

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageBase64, mediaType, fileName, offlineAnalysis } = await req.json();
    
    console.log(`\n=== ShanShield Cloud ML Analysis Request ===`);
    console.log(`Media Type: ${mediaType}`);
    console.log(`File: ${fileName}`);
    console.log(`Has Image: ${!!imageBase64}`);
    console.log(`Image Size: ${imageBase64 ? Math.round(imageBase64.length / 1024) : 0} KB`);

    // Run real ML analysis using Gemini Vision
    const mlResult = await analyzeWithGeminiVision(
      imageBase64,
      mediaType || 'image',
      fileName || 'unknown',
      offlineAnalysis || { score: 50, signals: [], details: {} }
    );

    // Calculate combined scores
    const offlineScore = offlineAnalysis?.score || 50;
    
    // For the combined confidence, we invert the logic:
    // If verdict is deepfake/suspicious, confidence represents how sure we are it's fake
    // We want to show this as a "manipulation score" on the frontend
    const mlScore = mlResult.verdict === 'deepfake' || mlResult.verdict === 'suspicious'
      ? 100 - mlResult.confidence  // Invert for suspicious/deepfake
      : mlResult.confidence;
    
    const combinedConfidence = Math.round(mlResult.confidence * 0.70 + (100 - offlineScore) * 0.30);

    const result = {
      verdict: mlResult.verdict,
      confidence: mlResult.confidence,
      mlSignals: mlResult.mlSignals,
      reasoning: mlResult.reasoning,
      aiToolDetected: mlResult.aiToolDetected,
      manipulationTypes: mlResult.manipulationTypes,
      combinedConfidence,
      offlineScore,
      mlScore: mlResult.confidence,
      analysisMode: "cloud_ml",
      modelUsed: "Gemini-3-Flash-Preview",
      geminiVersion: mlResult.geminiVersion || "gemini-3-flash-preview",
    };

    console.log(`Verdict: ${mlResult.verdict}`);
    console.log(`Confidence: ${mlResult.confidence}%`);
    console.log(`AI Tool Detected: ${mlResult.aiToolDetected || 'None'}`);
    console.log("=== Analysis Complete ===\n");

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error("ShanShield ML Analysis error:", error);
    
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    
    // Handle specific error codes
    if (errorMessage === "RATE_LIMIT") {
      return new Response(JSON.stringify({ 
        error: "Rate limit exceeded. Please try again in a moment.",
        code: "RATE_LIMIT"
      }), {
        status: 429,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    
    if (errorMessage === "PAYMENT_REQUIRED") {
      return new Response(JSON.stringify({ 
        error: "API credits exhausted. Please add credits to continue.",
        code: "PAYMENT_REQUIRED"
      }), {
        status: 402,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    
    return new Response(JSON.stringify({ 
      error: errorMessage,
      code: "ANALYSIS_ERROR"
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
