import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║                    SHANSHIELD CLOUD ML ANALYSIS                            ║
 * ║                                                                           ║
 * ║  Real AI-powered Deepfake Detection using Google Gemini                   ║
 * ║  Uses YOUR Gemini API Key (GEMINI_API_KEY) with Lovable Gateway fallback  ║
 * ║                                                                           ║
 * ║  FULL MEDIA ANALYSIS:                                                     ║
 * ║  - Video: 15+ frames for temporal consistency                             ║
 * ║  - Audio: Full-duration spectrogram image                                 ║
 * ║  - Image: Full resolution analysis                                        ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

interface OfflineAnalysisData {
  score: number;
  signals: string[];
  details: Record<string, { score: number; description: string }>;
  totalFramesAnalyzed?: number;
  totalSamplesAnalyzed?: number;
}

interface MLAnalysisResult {
  verdict: 'deepfake' | 'suspicious' | 'likely_authentic' | 'authentic';
  confidence: number;
  mlSignals: string[];
  reasoning: string;
  aiToolDetected: string | null;
  manipulationTypes: string[];
  geminiVersion?: string;
}

/**
 * System prompt for deepfake analysis - Optimized for Gemini
 */
const DEEPFAKE_ANALYSIS_PROMPT = `You are ShanShield, an expert AI system specialized in detecting AI-generated and manipulated media (deepfakes). Analyze the provided media for signs of AI generation or manipulation with extreme precision.

ANALYZE FOR:
1. **AI Generation Artifacts**: Look for telltale signs of AI image/video/audio generators like:
   - Unnatural skin textures or overly smooth areas
   - Inconsistent lighting or shadows
   - Warped or asymmetric facial features (especially ears, teeth, hands)
   - Artifacts around hair, teeth, ears, or jewelry
   - Unnatural eye reflections or catchlights
   - Background inconsistencies or blurring patterns
   - Text or symbols that are distorted

2. **Face Manipulation Signs**: Check for:
   - Boundary artifacts around face edges
   - Mismatched skin tones between face and body
   - Unnatural blending zones
   - Face swap seams or warping

3. **Technical Artifacts**: Identify:
   - Compression artifacts inconsistent with natural recordings
   - Color banding or posterization
   - Noise pattern irregularities (AI has uniform noise)

4. **AI Tool Signatures**: Try to identify if generated by:
   - Midjourney, Stable Diffusion, DALL-E, Flux
   - Sora, Runway, Kling, Pika (video)
   - ElevenLabs, Resemble.AI, Suno (audio)

5. **TEMPORAL ANALYSIS (for videos with multiple frames)**:
   - Compare faces across frames for consistency
   - Look for flickering or morphing artifacts
   - Check if lighting changes unnaturally between frames
   - Detect frame interpolation artifacts

6. **AUDIO SPECTROGRAM ANALYSIS**:
   - Look for unnaturally smooth frequency bands
   - Check for missing harmonic overtones
   - Identify synthetic voice patterns
   - Detect TTS artifacts (too-perfect pitch, unnatural rhythm)

RESPOND WITH EXACTLY THIS JSON FORMAT:
{
  "verdict": "deepfake" | "suspicious" | "likely_authentic" | "authentic",
  "confidence": <number 0-100>,
  "signals": ["signal1", "signal2", ...],
  "reasoning": "<detailed explanation in 2-3 sentences>",
  "aiToolDetected": "<tool name or null>",
  "manipulationTypes": ["type1", "type2", ...]
}

VERDICT GUIDELINES:
- "authentic": High confidence (85%+) the media is real
- "likely_authentic": Some minor concerns but probably genuine (60-84%)
- "suspicious": Notable anomalies suggesting possible manipulation (40-59%)
- "deepfake": Strong evidence of AI generation or manipulation (60%+ deepfake confidence)`;

/**
 * Call Gemini API directly using user's API key
 */
async function callGeminiDirect(
  apiKey: string,
  content: any[],
  model: string = "gemini-2.0-flash"
): Promise<any> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ role: "user", parts: content }],
      generationConfig: {
        temperature: 0.2,
        maxOutputTokens: 2000,
      },
      systemInstruction: { parts: [{ text: DEEPFAKE_ANALYSIS_PROMPT }] }
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("Gemini API error:", response.status, errorText);
    throw new Error(`Gemini API error: ${response.status}`);
  }

  return response.json();
}

/**
 * Fallback to Lovable AI Gateway
 */
async function callLovableGateway(
  apiKey: string,
  messages: any[]
): Promise<any> {
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-3-flash-preview",
      messages,
      temperature: 0.2,
      max_tokens: 2000,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("Lovable Gateway error:", response.status, errorText);
    if (response.status === 429) throw new Error("RATE_LIMIT");
    if (response.status === 402) throw new Error("PAYMENT_REQUIRED");
    throw new Error(`AI Gateway error: ${response.status}`);
  }

  return response.json();
}

/**
 * Analyze media using Gemini Vision
 */
async function analyzeWithGemini(
  imageBase64: string | null,
  videoFrames: string[] | undefined,
  spectrogramBase64: string | undefined,
  mediaType: string,
  fileName: string,
  offlineAnalysis: OfflineAnalysisData
): Promise<MLAnalysisResult> {
  const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
  
  // ALWAYS prefer Lovable Gateway (no quota issues) over direct Gemini API
  const useLovableGateway = !!LOVABLE_API_KEY;
  
  console.log(`Using ${useLovableGateway ? 'Lovable AI Gateway' : 'Direct Gemini API (fallback)'}`);

  // Helper to extract base64 data
  const extractBase64 = (dataUrl: string): { mimeType: string; base64Data: string } => {
    let base64Data = dataUrl;
    let mimeType = "image/jpeg";
    
    if (dataUrl.startsWith("data:")) {
      const matches = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (matches) {
        mimeType = matches[1];
        base64Data = matches[2];
      }
    }
    return { mimeType, base64Data };
  };

  // Build content parts for Gemini
  const parts: any[] = [];
  
  // For VIDEO with multiple frames
  if (mediaType === 'video' && videoFrames && videoFrames.length > 0) {
    console.log(`Processing ${videoFrames.length} video frames`);
    
    for (const frame of videoFrames) {
      const { mimeType, base64Data } = extractBase64(frame);
      parts.push({
        inline_data: { mime_type: mimeType, data: base64Data }
      });
    }
    
    parts.push({
      text: `Analyze these ${videoFrames.length} frames from video "${fileName}" for deepfake/AI-generation signs.
      
IMPORTANT: These are frames from DIFFERENT timestamps. Compare for:
- Temporal consistency (do faces look the same?)
- Flickering or morphing artifacts
- Lighting consistency across frames

Offline analysis (${offlineAnalysis.totalFramesAnalyzed || 0} total frames analyzed):
- Score: ${offlineAnalysis.score}/100
- Signals: ${offlineAnalysis.signals.join(", ") || "None"}

Provide your analysis in JSON format.`
    });
  }
  // For AUDIO with spectrogram
  else if (mediaType === 'audio' && spectrogramBase64) {
    console.log(`Processing audio spectrogram (${offlineAnalysis.totalSamplesAnalyzed || 0} samples)`);
    
    const { mimeType, base64Data } = extractBase64(spectrogramBase64);
    parts.push({
      inline_data: { mime_type: mimeType, data: base64Data }
    });
    
    parts.push({
      text: `Analyze this FULL AUDIO SPECTROGRAM from "${fileName}" for voice synthesis/AI-generation signs.

This spectrogram represents the ENTIRE audio file (${offlineAnalysis.totalSamplesAnalyzed || 0} samples).

Look for:
- Unnaturally smooth frequency bands (TTS artifacts)
- Missing harmonic overtones
- Too-perfect pitch patterns
- Synthetic voice characteristics
- ElevenLabs, Resemble.AI, or other voice cloning signatures

Offline audio analysis:
- Score: ${offlineAnalysis.score}/100
- Signals: ${offlineAnalysis.signals.join(", ") || "None"}
- Details: ${JSON.stringify(offlineAnalysis.details, null, 2)}

Provide your analysis in JSON format.`
    });
  }
  // For IMAGE
  else if (imageBase64) {
    const { mimeType, base64Data } = extractBase64(imageBase64);
    parts.push({
      inline_data: { mime_type: mimeType, data: base64Data }
    });
    
    parts.push({
      text: `Analyze this ${mediaType} "${fileName}" for deepfake/AI-generation signs.

Offline analysis:
- Score: ${offlineAnalysis.score}/100
- Signals: ${offlineAnalysis.signals.join(", ") || "None"}

Provide your analysis in JSON format.`
    });
  }
  // No visual - analyze based on offline data
  else {
    parts.push({
      text: `Analyze "${fileName}" based on offline forensic data:
- Score: ${offlineAnalysis.score}/100
- Signals: ${offlineAnalysis.signals.join(", ") || "None"}
- Details: ${JSON.stringify(offlineAnalysis.details, null, 2)}

Provide your assessment in JSON format.`
    });
  }

  let responseContent: string;
  let modelUsed: string;

  // ALWAYS prefer Lovable Gateway (pre-configured, no quota issues)
  if (useLovableGateway && LOVABLE_API_KEY) {
    console.log("Calling Lovable AI Gateway (gemini-3-flash-preview)...");
    
    // Convert parts to OpenAI format for gateway
    const userContent: any[] = [];
    for (const part of parts) {
      if (part.inline_data) {
        userContent.push({
          type: "image_url",
          image_url: { url: `data:${part.inline_data.mime_type};base64,${part.inline_data.data}` }
        });
      } else if (part.text) {
        userContent.push({ type: "text", text: part.text });
      }
    }
    
    const gatewayResponse = await callLovableGateway(LOVABLE_API_KEY, [
      { role: "system", content: DEEPFAKE_ANALYSIS_PROMPT },
      { role: "user", content: userContent }
    ]);
    
    responseContent = gatewayResponse.choices?.[0]?.message?.content || "";
    modelUsed = "google/gemini-3-flash-preview";
    console.log("Lovable Gateway response received");
  } else if (GEMINI_API_KEY) {
    // Fallback to direct Gemini API only if Lovable Gateway unavailable
    console.log("Calling Gemini API directly (fallback)...");
    const geminiResponse = await callGeminiDirect(GEMINI_API_KEY, parts);
    responseContent = geminiResponse.candidates?.[0]?.content?.parts?.[0]?.text || "";
    modelUsed = "gemini-2.0-flash";
    console.log("Gemini API response received");
  } else {
    throw new Error("No API key configured (LOVABLE_API_KEY or GEMINI_API_KEY)");
  }

  // Parse response
  try {
    let jsonStr = responseContent;
    const jsonMatch = responseContent.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (jsonMatch) {
      jsonStr = jsonMatch[1].trim();
    } else {
      const objMatch = responseContent.match(/\{[\s\S]*\}/);
      if (objMatch) jsonStr = objMatch[0];
    }

    const parsed = JSON.parse(jsonStr);
    
    return {
      verdict: parsed.verdict || 'suspicious',
      confidence: Math.max(0, Math.min(100, parsed.confidence || 50)),
      mlSignals: parsed.signals || [],
      reasoning: parsed.reasoning || 'Analysis completed',
      aiToolDetected: parsed.aiToolDetected || null,
      manipulationTypes: parsed.manipulationTypes || [],
      geminiVersion: modelUsed,
    };
  } catch (parseError) {
    console.error("Failed to parse response:", responseContent);
    return {
      verdict: offlineAnalysis.score > 70 ? 'suspicious' : 'likely_authentic',
      confidence: 100 - offlineAnalysis.score,
      mlSignals: ['Parsing error - using offline data'],
      reasoning: 'Cloud ML parsing issue. Using offline forensic analysis.',
      aiToolDetected: null,
      manipulationTypes: [],
    };
  }
}

// ============================================================================
// HTTP SERVER
// ============================================================================

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageBase64, videoFrames, spectrogramBase64, mediaType, fileName, offlineAnalysis } = await req.json();
    
    console.log(`\n=== ShanShield Cloud ML Analysis ===`);
    console.log(`Media Type: ${mediaType}`);
    console.log(`File: ${fileName}`);
    console.log(`Has Image: ${!!imageBase64}`);
    console.log(`Video Frames: ${videoFrames?.length || 0}`);
    console.log(`Has Spectrogram: ${!!spectrogramBase64}`);
    console.log(`Offline Frames Analyzed: ${offlineAnalysis?.totalFramesAnalyzed || 'N/A'}`);
    console.log(`Offline Samples Analyzed: ${offlineAnalysis?.totalSamplesAnalyzed || 'N/A'}`);

    const mlResult = await analyzeWithGemini(
      imageBase64,
      videoFrames,
      spectrogramBase64,
      mediaType || 'image',
      fileName || 'unknown',
      offlineAnalysis || { score: 50, signals: [], details: {} }
    );

    const offlineScore = offlineAnalysis?.score || 50;
    const combinedConfidence = Math.round(mlResult.confidence * 0.70 + (100 - offlineScore) * 0.30);

    const result = {
      verdict: mlResult.verdict,
      confidence: mlResult.confidence,
      mlSignals: mlResult.mlSignals,
      reasoning: mlResult.reasoning,
      aiToolDetected: mlResult.aiToolDetected,
      manipulationTypes: mlResult.manipulationTypes,
      combinedConfidence,
      offlineScore,
      mlScore: mlResult.confidence,
      analysisMode: "cloud_ml",
      modelUsed: mlResult.geminiVersion || "Gemini",
      geminiVersion: mlResult.geminiVersion,
    };

    console.log(`✅ Verdict: ${mlResult.verdict} (${mlResult.confidence}%)`);
    console.log(`   AI Tool: ${mlResult.aiToolDetected || 'None'}`);
    console.log("=== Analysis Complete ===\n");

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error("Analysis error:", error);
    
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    
    if (errorMessage === "RATE_LIMIT") {
      return new Response(JSON.stringify({ 
        error: "Rate limit exceeded. Please try again.",
        code: "RATE_LIMIT"
      }), {
        status: 429,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    
    if (errorMessage === "PAYMENT_REQUIRED") {
      return new Response(JSON.stringify({ 
        error: "API credits exhausted.",
        code: "PAYMENT_REQUIRED"
      }), {
        status: 402,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    
    return new Response(JSON.stringify({ 
      error: errorMessage,
      code: "ANALYSIS_ERROR"
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
